const responseList = [
    {
      info: {
        id: "337899",
        name: "The Paratha House",
        cloudinaryImageId: "jhjyc3xjdbkqr9wbzsj7",
        locality: "Ganesh Chowk",
        areaName: "Chhindwara Locality",
        costForTwo: "₹150 for two",
        cuisines: ["North Indian"],
        avgRating: 4.2,
        veg: true,
        parentId: "3035",
        avgRatingString: "4.2",
        totalRatingsString: "30",
        sla: {
          deliveryTime: 54,
          lastMileTravel: 10.3,
          serviceability: "SERVICEABLE",
          slaString: "50-55 mins",
          lastMileTravelString: "10.3 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      info: {
        id: "382152",
        name: "Shriji Namkeen",
        cloudinaryImageId: "wa8ek94fp9d97ru1tcyn",
        locality: "Palika Market",
        areaName: "Chhindwara City",
        costForTwo: "₹250 for two",
        cuisines: ["Snacks", "Beverages", "Desserts"],
        avgRating: 3.8,
        parentId: "187168",
        avgRatingString: "3.8",
        totalRatingsString: "48",
        sla: {
          deliveryTime: 55,
          lastMileTravel: 10.7,
          serviceability: "SERVICEABLE",
          slaString: "50-55 mins",
          lastMileTravelString: "10.7 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      info: {
        id: "751057",
        name: "The Burger House",
        cloudinaryImageId: "7fb21fceb84ef1f1e5377cf25fd46247",
        locality: "Vip Khajri Road",
        areaName: "Chhindwara City",
        costForTwo: "₹300 for two",
        cuisines: ["Burgers", "Snacks", "Beverages"],
        veg: true,
        parentId: "16588",
        avgRatingString: "--",
        sla: {
          deliveryTime: 62,
          lastMileTravel: 11.4,
          serviceability: "SERVICEABLE",
          slaString: "60-65 mins",
          lastMileTravelString: "11.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
  ];

export default responseList;